### ISSUE TITLE
Pasted layouts are not retaining offset

### ISSUE THREAD

**Issue by scottalonzo** [FrancisVega/sketch-copy-paste-layout-settings#4]
When pasting layouts, settings and proportions are retained but the pasted layout always re-centers itself, even if the copied layout had a non-centered offset.

Sketch 46.2 on Mac OS 10.12.6

**Comment by scottalonzo** [comment]
Expected behaviour can be achieved by changing line 81 from:

`abLayout.horizontalOffset = (artboard.frame().width() - layout.totalWidth) / 2;`

to

`abLayout.horizontalOffset = layout.horizontalOffset;`

**Comment by FrancisVega** [comment]
Fixed. Thank you very much! :)
