### ISSUE TITLE
Not working with Sketch 48.2

### ISSUE THREAD

**Issue by timtomtoo** [FrancisVega/sketch-copy-paste-layout-settings#7]
Thanks for this. Would be a huge lifesaver but it isn't appearing to copy or paste in Sketch 48.2.

**Comment by julienphuez** [comment]
The layout settings are copied but don't display.
But when you display the layout settings, it's appearing :/
So it's not working totally

**Comment by FrancisVega** [comment]
Fixed! Thanks for the comments!
