### ISSUE TITLE
update not available

### ISSUE THREAD

**Issue by pierrelucgagnon** [FrancisVega/sketch-copy-paste-layout-settings#8]
Sketch [49.3] has been prompting an update message for this plugin for about two weeks now, but it won't update when clicking the update button on the plugin manager window. There seems to have a 1.0 version but the only one that's available is 0.8.

**Comment by FrancisVega** [comment]
I made changes in the metadata plugin some days ago. To fix that you have to re-install the plugin again (v1.0) :S

**Comment by pierrelucgagnon** [comment]
Unfortunately it's not working for me :( I made a little screen cast if that can be of any help : https://youtu.be/tZ_e9orqjIQ

**Comment by FrancisVega** [comment]
Hi @pierrelucgagnon 

**First** uninstall the plugin from Sketch.

<img width="522" alt="captura de pantalla 2018-04-26 a las 13 06 54" src="https://user-images.githubusercontent.com/906119/39302409-ccc87e20-4952-11e8-897c-68676f8a76b3.png">

**Comment by pierrelucgagnon** [comment]
Hi @FrancisVega, thanks for the support. Yes, I did try that too. I made another video to show you: https://youtu.be/nKBeZY0wK1c

**Comment by FrancisVega** [comment]
Hi @pierrelucgagnon. It seems that the link is in some way wrong (I'm going to check what happens). Try to download it from the download option:

![captura de pantalla 2018-04-26 a las 21 12 55](https://user-images.githubusercontent.com/906119/39326970-e54f417e-4996-11e8-9fa3-edcacee7e461.png)

Sorry for that :(

**Comment by pierrelucgagnon** [comment]
Got it, it's now running version 1.0.0. Thanks for your time, and for developing this very useful plugin as well! Cheers from Montreal, Canada.
